### NUMPY

In [1]:
import numpy as np

### Beginer Questions - The Basics

Q1 . Create from a List: Create a 2D NumPy array from the following Python list: [[10, 20, 30], [40, 50, 60]].

In [2]:
l1 = [10,20,30]
l2 = [40,50,60]
arr = np.array([l1,l2])
print(arr)

[[10 20 30]
 [40 50 60]]


Q2 . Generate a Sequence: Create a 1D array containing all integers from 10 to 49.

In [4]:
arr1 = np.arange(10,50,1)
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Q3 . Create a Matrix of Ones: Create a 3x3 matrix where all elements are the number 1.

In [5]:
one_arary = np.ones((3,3))
print(one_arary)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Q4 . Find Attributes: For the array you created in question 1, find its shape, size, and data type

In [11]:
print(arr.shape , arr.size , arr.dtype)

(2, 3) 6 int64


Q5 . Basic Indexing: From the array [[1, 2, 3], [4, 5, 6], [7, 8, 9]], select the element 6.

In [20]:
arr5  = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr5[1][2])
print(arr5[:2,1:])

6
[[2 3]
 [5 6]]


### Level 2 - Data Wrangling and manipulation

Q1 Reshape an Array: Create a 1D array of 12 consecutive numbers starting from 0. Reshape it into a 4x3 matrix.

In [21]:
arr1 = np.arange(0,12)
arr1 = arr1.reshape((4,3))
print(arr1)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


Q2 Boolean Filtering: Given an array A = np.arange(10), create a new array that contains only the elements of A that are greater than 5.

In [22]:
A = np.arange(10)
B = A[A > 5]
print(B)

[6 7 8 9]


Q3 Conditional Replacement: Given the array A from the previous question, create a new array where all odd numbers are replaced with -1. (Hint: Use np.where).

In [29]:
C = np.where(A%2==1,A,-1)
print(C)

[-1  1 -1  3 -1  5 -1  7 -1  9]



### Your Swapped Code ✅

`np.where(A % 2 == 1, A, -1)`

Now let's translate this version:

  * **Condition**: Is the number odd (`A % 2 == 1`)? (This is still the same condition).
  * **Value if `True`**: If it *is* odd, use the original number from `A`.
  * **Value if `False`**: If it *is not* odd (meaning it's even), use `-1`.

**Result**: Even numbers become -1.

So, by swapping the last two parameters, you flipped the logic of which numbers get replaced.

Here's the code to prove it:

```python
import numpy as np
A = np.arange(10) # A is [0 1 2 3 4 5 6 7 8 9]

# Original: Odd numbers become -1
C_original = np.where(A % 2 == 1, -1, A)
print("Original logic:", C_original)
# Output: Original logic: [ 0 -1  2 -1  4 -1  6 -1  8 -1]

# Swapped: Even numbers become -1
C_swapped = np.where(A % 2 == 1, A, -1)
print("Swapped logic: ", C_swapped)
# Output: Swapped logic:  [-1  1 -1  3 -1  5 -1  7 -1  9]
```

Q4 Stacking Arrays: Given two arrays, a = np.arange(1, 5) and b = np.arange(5, 9), stack them vertically (to create 2 rows) and then horizontally (to create a single long row)

In [32]:
a = np.arange(1,5)
b = np.arange(5,9)
c = np.array([a,b])
d = np.append(a,b)
d

array([1, 2, 3, 4, 5, 6, 7, 8])

Q5 Find Common Items: Find the common values between two arrays: a = np.array([1, 2, 3, 4, 5]) and b = np.array([3, 5, 7, 9]). (Hint: Look into np.intersect1d).

In [33]:
a = np.array([1,2,3,4,5])
b = np.array([3,5,6,7,9])
c = np.intersect1d(b,a)
c

array([3, 5])

### Level 3: Statistics & Data Analysis

imagine you have the following dataset representing the scores of 4 students in 3 subjects.
scores = np.array([[80, 85, 90], [75, 88, 92], [90, 91, 86], [82, 80, 84]])
Where each row is a student and each column is a subject.

Q1 Calculate Overall Mean: Find the average score across all subjects for all students.

In [40]:
scores = np.array([[80,85,90],[75,88,92],[82,80,84]])
avg_marks = []
for i in scores:
    avg_marks.append(np.mean(i))
avg_marks = np.array(avg_marks)
print(avg_marks)

[85. 85. 82.]


Q2. Calculate Mean by Subject: Find the average score for each subject. The result should be a 1D array with 3 values. (Hint: Use the axis parameter).

In [42]:
scores = np.array([[80,85,90],[75,88,92],[82,80,84]])
avg_sub = np.array(np.mean(scores,axis=0))
print(avg_sub)

[79.         84.33333333 88.66666667]


Q3 Find the Best Student: Find the average score for each student and identify which student (which row index) has the highest average. (Hint: Use mean with the correct axis, then np.argmax).

In [46]:
means = np.mean(scores,axis=1)
means = list(means)
print(np.array(means.index(max(means))))
# does the same thing as above 2 lines
print(np.argmax(means))

0
0


Q4 Normalize Data (Standardization): Normalize the scores matrix. For each column (subject), subtract its mean and divide by its standard deviation. This process, called standardization, is a critical preprocessing step in machine learning. 🤓

Formula for standardization: Z= 
σ
X−μ

In [48]:
scores_t = scores.T
norm_score_sub = np.zeros(scores_t.shape)
sd = []
means = []
for i in scores_t:
    sd.append(np.std(i))
    means.append(np.mean(i))
for i in range(0,len(sd)):
    norm_score_sub[i] = (scores_t[i] - means[i])/sd[i]

print(norm_score_sub)


[[ 0.33968311 -1.35873244  1.01904933]
 [ 0.20203051  1.1111678  -1.31319831]
 [ 0.39223227  0.98058068 -1.37281295]]


### Level 4: Machine Learning & Linear Algebra

Q1. Calculate Euclidean Distance: Create a function that takes two 1D arrays (vectors) of the same size and returns their Euclidean distance. This is the core of algorithms like K-Nearest Neighbors (k-NN).

In [ ]:
def euclidean_distacne(arr1,arr2):
    arr = np.array(np.sqrt(np.sum(np.square(arr1-arr2))))
    print(arr)
    return arr
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr3 = euclidean_distacne(arr1,arr2)

11.180339887498949


Q2. One-Hot Encode Labels: You have an array of labels labels = np.array([0, 2, 1, 0, 1]). Convert this into a one-hot encoded matrix. The result should be a 5x3 matrix where the column corresponding to the label is 1 and the rest are 0.

In [55]:
labels = np.array([0, 2, 1, 0, 1])
list_l = []
for i in labels:
    if i not in list_l:
        list_l.append(i)
list_l = np.array(list_l)
encode = np.zeros((len(list_l),len(labels)))
for index, value in enumerate(labels):
  encode[value][index] = 1
print(encode)


[[1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 1.]
 [0. 1. 0. 0. 0.]]


Q3. Solve for Linear Regression Weights: This is a classic! Given a feature matrix X and a target vector y, calculate the optimal weights w using the Normal Equation

In [56]:
X = np.array([[1, 2], [1, 3], [1, 4]]) # Don't forget the bias term (first column of 1s)
y = np.array([3, 5, 6])

mul_comp = np.linalg.inv(X.T @ X)
final_answer = mul_comp @ X.T @ y

print(final_answer)

[0.16666667 1.5       ]
